import type { NextPage } from "next";
import Head from "next/head";
import { About } from "src/components/pages/about";

const AboutPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="icons/favicon.ico" />
      </Head>
      <About />
    </>
  );
};

export default AboutPage;
